### ISSUE TITLE
Error 'django.core.urlresolvers.NoReverseMatch' after login

### ISSUE THREAD

**Issue by liyaka** [big-data-europe/docker-hdfs-filebrowser#3]
I'm trying to run this docker according to your instructions . I get this error after login:
django.core.urlresolvers.NoReverseMatch
NoReverseMatch: u'about' is not a registered namespace

**Comment by earthquakesan** [comment]
@liyaka hi! Sorry for late answer. The problem is that I disabled 'about' screen, you need to append /home path to the URI like http://localhost:8088/home

**Comment by dimisjim** [comment]
@earthquakesan What do you mean by "disabled about screen" ?

**Comment by earthquakesan** [comment]
@dimisjim /about path is disabled

**Comment by dimisjim** [comment]
@earthquakesan How can I re-enable it?

**Comment by earthquakesan** [comment]
@dimisjim you can edit entrypoint and remote about from blacklisted list: https://github.com/big-data-europe/docker-hdfs-filebrowser/blob/master/entrypoint.sh

I would not recommend doing this, because about screen was hanging the whole application.

**Comment by dimisjim** [comment]
@earthquakesan hmm I see.

So what would be a quick alternative, to have Hue spawn to /home, right after sign up?

**Comment by earthquakesan** [comment]
if you point your users to /home, then the login screen will have ?next=/home as a parameter and after login the user will be redirected there.
